const config = {
	APP_TITLE: "RNIAP Sample",
	BASE_URL: "YOUR BASE URL",
	IOS_SUBSCRIPTION_ID: "YOUR IOS SUBSCRIPTION ID",
	ANDROID_SUBSCRIPTION_ID: "YOUR ANDROID SUBSCRIPTION ID",
};

export default config;
